name: CI
on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up php 8.0
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Run env
        run: |
          echo "${{secrets.RAZORPAY}}"
      - name: Install dependencies
        run: composer install && composer dump-autoload
      - name: 'Create env file'
        run: |
          touch .env
          echo API_ENDPOINT="https://xxx.execute-api.us-west-2.amazonaws.com" >> ${{ github.workspace }}/tests/ .env
          echo API_KEY=${{ secrets.RAZORPAY }} >> ${{ github.workspace }}/tests/ .env
          cat ${{ github.workspace }}/tests/ .env
      - name: Install dependencies
        run: composer self-update && composer install && composer require vlucas/phpdotenv && composer dump-autoload
      - name: Run tests and collect coverage
        #run: vendor/bin/phpunit TestCase.php    
